name: hf39
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - accelerate=0.33.0
  - affine=2.4.0
  - aiohappyeyeballs=2.3.5
  - aiohttp=3.10.3
  - aiosignal=1.3.1
  - alembic=1.13.2
  - annotated-types=0.7.0
  - arrow=1.3.0
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - blas=1.0
  - blinker=1.8.2
  - blosc=1.21.6
  - boost-cpp=1.78.0
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - cairo=1.18.0
  - catalogue=2.0.10
  - certifi=2024.8.30
  - cffi=1.16.0
  - cfitsio=4.4.1
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpathlib=0.20.0
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorlog=6.8.2
  - confection=0.1.4
  - contourpy=1.2.1
  - cookiecutter=2.6.0
  - coverage=7.6.9
  - cryptography=43.0.3
  - cuda-cccl=12.6.37
  - cuda-cccl_win-64=12.6.37
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.0
  - cuda-libraries-dev=12.4.0
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.37
  - cuda-opencl-dev=12.6.37
  - cuda-profiler-api=12.6.37
  - cuda-version=12.6
  - cupy=13.3.0
  - cupy-core=13.3.0
  - cycler=0.12.1
  - cymem=2.0.8
  - cython=3.0.11
  - cython-blis=0.7.10
  - datasets=2.20.0
  - dill=0.3.8
  - editdistance=0.6.2
  - et_xmlfile=1.1.0
  - evaluate=0.4.1
  - exceptiongroup=1.2.2
  - expat=2.6.3
  - fastrlock=0.8.2
  - filelock=3.15.4
  - fiona
  - flask=3.0.0
  - fmt=11.0.2
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.4.1
  - fsspec=2024.5.0
  - ftfy=6.2.3
  - gdal=3.9.2
  - geopandas
  - geopandas-base
  - geos=3.12.2
  - geotiff=1.7.3
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - google-api-core=2.21.0
  - google-api-python-client=2.149.0
  - google-auth=2.35.0
  - google-auth-httplib2=0.2.0
  - googleapis-common-protos=1.65.0
  - h2=4.1.0
  - h5netcdf=1.3.0
  - h5py=3.11.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - httplib2=0.22.0
  - huggingface_hub=0.24.5
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=8.2.0
  - importlib-resources=6.4.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - itsdangerous=2.2.0
  - jellyfish=1.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - langcodes=3.4.1
  - language-data=1.2.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.4.2.65
  - libcublas-dev=12.4.2.65
  - libcufft=11.2.0.44
  - libcufft-dev=11.2.0.44
  - libcurand=10.3.7.37
  - libcurand-dev=10.3.7.37
  - libcurl=8.10.1
  - libcusolver=11.6.0.99
  - libcusolver-dev=11.6.0.99
  - libcusparse=12.3.0.142
  - libcusparse-dev=12.3.0.142
  - libdeflate=1.21
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgdal=3.9.2
  - libgdal-core=3.9.2
  - libgdal-fits=3.9.2
  - libgdal-grib=3.9.2
  - libgdal-hdf4=3.9.2
  - libgdal-hdf5=3.9.2
  - libgdal-jp2openjpeg=3.9.2
  - libgdal-kea=3.9.2
  - libgdal-netcdf=3.9.2
  - libgdal-pdf=3.9.2
  - libgdal-pg=3.9.2
  - libgdal-postgisraster=3.9.2
  - libgdal-tiledb=3.9.2
  - libgdal-xls=3.9.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.3
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnpp=12.2.5.2
  - libnpp-dev=12.2.5.2
  - libnvfatbin=12.6.20
  - libnvfatbin-dev=12.6.20
  - libnvjitlink=12.4.99
  - libnvjitlink-dev=12.4.99
  - libnvjpeg=12.3.1.89
  - libnvjpeg-dev=12.3.1.89
  - libparquet=17.0.0
  - libpng=1.6.44
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libspatialindex=2.0.0
  - libspatialite=5.1.0
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzip=1.10.1
  - libzlib=1.3.1
  - lightning-utilities=0.11.7
  - lxml=5.3.0
  - lz4-c=1.9.4
  - lzo=2.10
  - mako=1.3.5
  - mapclassify=2.7.0
  - marisa-trie=1.2.0
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-base=3.9.1
  - mdurl=0.1.2
  - minizip=4.0.6
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munch=4.0.0
  - munkres=1.1.4
  - murmurhash=1.0.10
  - networkx=3.2.1
  - numexpr=2.7.3
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.4.0
  - optuna=3.6.1
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.0.3
  - parsimonious=0.10.0
  - pathvalidate=3.2.1
  - patsy=0.5.6
  - pcre2=10.44
  - pillow=10.3.0
  - pip=24.0
  - pluggy=1.5.0
  - poppler=24.08.0
  - poppler-data=0.4.12
  - postgresql=16.4
  - preshed=3.0.9
  - prettytable=0.7.2
  - proj=9.5.0
  - proto-plus=1.25.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - psycopg2=2.9.9
  - psycopg2-binary=2.9.9
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pyparsing=3.1.2
  - pypdf=4.3.1
  - pyproj=3.6.1
  - pysocks=1.7.1
  - pytest=8.3.4
  - pytest-cov=6.0.0
  - python=3.9
  - python-dateutil=2.9.0
  - python-docx=1.1.2
  - python-slugify=8.0.4
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.9
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - qhull=2020.2
  - rapidfuzz=3.10.1
  - rasterio=1.3.11
  - re2=2023.09.01
  - recordlinkage=0.16
  - regex=2024.7.24
  - requests=2.32.3
  - responses=0.18.0
  - retrying=1.3.3
  - rich=13.7.1
  - rioxarray=0.15.0
  - rsa=4.9
  - rtree=1.3.0
  - safetensors=0.4.4
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - setuptools=71.0.4
  - shapely=2.0.6
  - shellingham=1.5.4
  - six=1.16.0
  - smart-open=7.0.5
  - smart_open=7.0.5
  - snappy=1.2.1
  - snuggs=1.4.7
  - soupsieve=2.5
  - spacy=3.7.6
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - spdlog=1.14.1
  - sqlalchemy=2.0.20
  - sqlite=3.46.1
  - srsly=2.4.8
  - statsmodels=0.14.4
  - striprtf=0.0.26
  - sympy=1.13.2
  - tbb=2021.12.0
  - text-unidecode=1.3
  - thinc=8.2.5
  - threadpoolctl=3.5.0
  - tiledb=2.25.0
  - tk=8.6.13
  - tokenizers=0.19.1
  - toml=0.10.2
  - tomli=2.2.1
  - torchmetrics=1.4.2
  - tqdm=4.66.5
  - transformers=4.44.0
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - uritemplate=4.1.1
  - urllib3=2.2.2
  - waitress=1.4.4
  - wasabi=1.1.2
  - wcwidth=0.2.13
  - weasel=0.4.1
  - werkzeug=3.0.1
  - wheel=0.43.0
  - wrapt=1.16.0
  - xarray=2024.7.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - filelock
  - earthengine-api
